### PR TITLE
AppRole support

### PR DESCRIPTION
**Pull request by kotyara85**

### CODE REVIEW

**Comment by kotyara85** [comment]
@tamalsaha  this pr seems to be failing because of some missing docker credentials. Is this something you can fix in the pipeline?
Thanks

**Comment by tamalsaha** [comment]
@kotyara85  , the issue is Github actions does not make secret available to forked repo. 

- https://github.community/t5/GitHub-Actions/Make-secrets-available-to-builds-of-forks/m-p/30678
- https://github.community/t5/GitHub-Actions/Allow-secrets-to-be-shared-with-forks-from-trusted-Actions/m-p/34278

There is nothing I can do to fix the CI issue.  :(

**Comment by tamalsaha** [comment]
I have created a draft pr from this repo so we can run the full tests.

**Comment by kotyara85** [comment]
Gotcha.
I'm actually think of moving the logic to VaultPolicyBinding. Which will make more sense rather to introducing new watchers.

**Comment by tamalsaha** [comment]
@kotyara85 , I have written a summary of things can be done to fully support AppRole here: https://github.com/kubevault/project/pull/98 . Can you please take a look so we can work out a high level design before I dive into code reviewing this pr?

**Comment by kotyara85** [comment]
> @kotyara85 , I have written a summary of things can be done to fully support AppRole here: [kubevault/project#98](https://github.com/kubevault/project/pull/98) . Can you please take a look so we can work out a high level design before I dive into code reviewing this pr?

Here're my comments as I'm pretty familiar with the approle flow - 
1 - agree
2 - doing this step right now, finalizer should be in place so we don't have any garbage
3 - you need to create policies which will allow endusers auth against vault and run these commands  using token/ldap/oidc/jwt auth. Or an admin can generate these.
to get role-id:
`vault read auth/approle/role/<ROLE_NAME>/role-id`
to generate a new secret-id
`vault write -f auth/approle/role/<ROLE_NAME>/secret-id`
4 - I don't think you really need this unless you want to use it as a mechanism for kubevault to auth to vault servers. approles are meant to be used by external applications mainly. Jenkins as an example, so it can connect to vault and pull required secrets
5 -

**Comment by kotyara85** [comment]
@tamalsaha pushed an update per reqs. building now. you can close #267 cause it's not relevant anymore

**Comment by kotyara85** [comment]
> @kotyara85 , please let me know when the pr is ready for review.

it's ready for review!

**Comment by tamalsaha** [comment]
Thanks @kotyara85 . @kamolhasan is going to work on fixing the e2e test set up this week. We have moved the test credentials to a bot account from individual developer accounts. I would like to get the tests passing again before we start merging prs. So, bear with me.

**Comment by tamalsaha** [comment]
@kotyara85 , sorry for the long delay. E2e tests are passing in master. Also, we have fixed various retry issues in existing controller. Please take a look at the new code and rebase your pr. We should be able to merge and release soon.

**Comment by kotyara85** [comment]
@tamalsaha rebased and pushed

**Comment by tamalsaha** [comment]
Thanks for your contribution!

**Pull request merged**
