### PR TITLE
Raft backend

### PR DESCRIPTION
**Pull request by yoan-adfinis**
A follow up of this closed Pull Request from @cabrinha a while ago, https://github.com/kubevault/operator/pull/262

### CODE REVIEW

**Comment by karras** [comment]
This fixes https://github.com/kubevault/project/issues/96

**Comment by tamalsaha** [comment]
Thanks! Can you fix https://github.com/kubevault/operator/pull/279/checks?check_run_id=876975968 ?

**Comment by yoan-adfinis** [comment]
@cabrinha @karras do you mind if I alter the commits of yours?

**Comment by karras** [comment]
@yoan-adfinis Fine for me if still necessary :)

**Comment by cabrinha** [comment]
> @cabrinha @karras do you mind if I alter the commits of yours?

Feel free to edit my commits!

**Comment by tamalsaha** [comment]
Reopened in https://github.com/kubevault/operator/pull/334

**Pull request closed without merging**
